version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight-service-website
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      # Placeholder for future environment variables
      - NODE_ENV=production
    volumes:
      # Optional: Mount for development hot-reload
      # Uncomment the following lines for development
      # - ./src:/app/src:ro
      # - ./dist:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - flight-service-network

networks:
  flight-service-network:
    driver: bridge
